# -*- coding: utf-8 -*-
# Author: Serhii Barskyi | https://www.linkedin.com/in/serhii-barskyi/
# Data Science Course: https://preply.com/en/tutor/7756455
# Framework: Complex Spectral Surrogate Framework (CSSF)
#
# Licensed under the Apache License, Version 2.0.
# You may not use this file except in compliance with the License.
# Full license text: https://www.apache.org/licenses/LICENSE-2.0
#
# Attribution required: if you use this code, please cite:
# Serhii Barskyi, Complex Spectral Surrogate Framework (CSSF),
# https://www.linkedin.com/in/serhii-barskyi/

"""Safe adapter around the frozen CSNN-T mathematical implementation.

The adapter allows every CSSF surrogate level to reuse the unchanged
``core/gcv.py`` and ``core/csnn_t.py`` primitive:

    H = (XᴴX + λI)⁻¹XᴴY,
    Ŷ = Re(XH).

It adds strict validation, immutable coefficients, GCV diagnostics, dataset
conversion, target names, fingerprints, and frozen-core integrity checks.
It never rewrites or monkey-patches the legacy modules.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np
from numpy.typing import ArrayLike, NDArray

from core.csnn_t import CSNNTModel, fit_csnn_t
from core.dataset import BESSDataset, CSSFDataset, DatasetError
from core.gcv import effective_rank, gcv_lambda
from core.types import SurrogateLevel
from core.validation import (
    COLAB_PROJECT_ROOT,
    CSSFValidationError,
    verify_frozen_core,
)


class CSNNTAdapterError(RuntimeError):
    """Raised when adapter input or output violates the CSNN-T contract."""


def _validated_features(
    values: ArrayLike,
    *,
    expected_features: int,
) -> NDArray[np.complex128]:
    """Return a finite contiguous complex feature matrix."""

    array = np.asarray(values)

    if array.ndim != 2:
        raise CSNNTAdapterError(
            f"features must be two-dimensional; received {array.shape}."
        )
    if array.shape[0] == 0:
        raise CSNNTAdapterError("features must contain at least one sample.")
    if array.shape[1] != expected_features:
        raise CSNNTAdapterError(
            f"features contain {array.shape[1]} columns; "
            f"expected {expected_features}."
        )

    result = np.ascontiguousarray(array, dtype=np.complex128)

    if not np.all(np.isfinite(result.real)):
        raise CSNNTAdapterError(
            "features contain non-finite real components."
        )
    if not np.all(np.isfinite(result.imag)):
        raise CSNNTAdapterError(
            "features contain non-finite imaginary components."
        )

    return result


def _normalized_target_names(
    values: Sequence[str] | None,
    *,
    count: int,
) -> tuple[str, ...]:
    """Validate target names or create deterministic defaults."""

    if values is None:
        return tuple(f"target_{index:04d}" for index in range(count))

    names = tuple(str(value).strip() for value in values)

    if len(names) != count:
        raise CSNNTAdapterError(
            f"target_names length must equal {count}; received {len(names)}."
        )
    if any(not name for name in names):
        raise CSNNTAdapterError("target_names must not contain empty values.")
    if len(set(names)) != len(names):
        raise CSNNTAdapterError("target_names must be unique.")

    return names


def _readonly_real_vector(
    values: ArrayLike,
) -> NDArray[np.float64]:
    """Return an immutable real vector."""

    result = np.ascontiguousarray(values, dtype=np.float64).reshape(-1)
    result.setflags(write=False)
    return result


@dataclass(frozen=True, slots=True)
class CSNNTFitDiagnostics:
    """Regularization diagnostics generated by the frozen GCV functions."""

    lam_opt: float
    effective_rank: float
    n_lambdas: int
    lam_range: tuple[float, float]
    used_fixed_lambda: bool
    lam_grid: NDArray[np.float64]
    gcv_values: NDArray[np.float64]

    def __post_init__(self) -> None:
        lam_opt = float(self.lam_opt)
        rank = float(self.effective_rank)

        if not math.isfinite(lam_opt) or lam_opt <= 0.0:
            raise CSNNTAdapterError("lam_opt must be finite and positive.")
        if not math.isfinite(rank) or rank < 0.0:
            raise CSNNTAdapterError(
                "effective_rank must be finite and non-negative."
            )
        if self.n_lambdas < 0:
            raise CSNNTAdapterError("n_lambdas must be non-negative.")

        lam_grid = _readonly_real_vector(self.lam_grid)
        gcv_values = _readonly_real_vector(self.gcv_values)

        if lam_grid.shape != gcv_values.shape:
            raise CSNNTAdapterError(
                "lam_grid and gcv_values must have equal shapes."
            )
        if self.used_fixed_lambda:
            if lam_grid.size != 0 or gcv_values.size != 0:
                raise CSNNTAdapterError(
                    "Fixed-lambda diagnostics must not contain a GCV grid."
                )
        elif lam_grid.size != self.n_lambdas:
            raise CSNNTAdapterError(
                "GCV grid size must equal n_lambdas."
            )

        object.__setattr__(self, "lam_opt", lam_opt)
        object.__setattr__(self, "effective_rank", rank)
        object.__setattr__(self, "lam_grid", lam_grid)
        object.__setattr__(self, "gcv_values", gcv_values)

    def as_dict(self) -> dict[str, Any]:
        """Return JSON-compatible scalar diagnostics."""

        return {
            "lam_opt": self.lam_opt,
            "effective_rank": self.effective_rank,
            "n_lambdas": self.n_lambdas,
            "lam_range": list(self.lam_range),
            "used_fixed_lambda": self.used_fixed_lambda,
            "gcv_min": (
                None
                if self.gcv_values.size == 0
                else float(np.min(self.gcv_values))
            ),
        }


@dataclass(frozen=True, slots=True)
class CSNNTSurrogateModel:
    """Validated wrapper around the frozen ``CSNNTModel``."""

    frozen_model: CSNNTModel
    level: SurrogateLevel
    target_names: tuple[str, ...]
    training_fingerprint: str
    diagnostics: CSNNTFitDiagnostics
    metadata: Mapping[str, Any]

    def __post_init__(self) -> None:
        if not isinstance(self.frozen_model, CSNNTModel):
            raise TypeError("frozen_model must be CSNNTModel.")
        if not isinstance(self.level, SurrogateLevel):
            raise TypeError("level must be SurrogateLevel.")
        if len(self.target_names) != self.frozen_model.n:
            raise CSNNTAdapterError(
                "target_names count must equal frozen_model.n."
            )
        if len(self.training_fingerprint) != 64:
            raise CSNNTAdapterError(
                "training_fingerprint must be a SHA-256 hexadecimal digest."
            )

    @property
    def H(self) -> NDArray[np.complex128]:
        """Immutable spectral coefficient matrix."""

        return self.frozen_model.H

    @property
    def lam_opt(self) -> float:
        """Selected Tikhonov regularization parameter."""

        return float(self.frozen_model.lam_opt)

    @property
    def case(self) -> str:
        """Dataset case identifier."""

        return self.frozen_model.case

    @property
    def n_features(self) -> int:
        """Number of complex spectral features."""

        return int(self.frozen_model.M)

    @property
    def n_targets(self) -> int:
        """Number of real target columns."""

        return int(self.frozen_model.n)

    def predict(self, features: ArrayLike) -> NDArray[np.float64]:
        """Predict ``Re(XH)`` using the unchanged frozen model."""

        validated = _validated_features(
            features,
            expected_features=self.n_features,
        )
        prediction = np.ascontiguousarray(
            self.frozen_model.predict(validated),
            dtype=np.float64,
        )

        if prediction.shape != (validated.shape[0], self.n_targets):
            raise CSNNTAdapterError(
                "Frozen model returned an unexpected prediction shape."
            )
        if not np.all(np.isfinite(prediction)):
            raise CSNNTAdapterError(
                "Frozen model returned non-finite predictions."
            )

        return prediction

    def mean_prediction(self, features: ArrayLike) -> NDArray[np.float64]:
        """Return the mean predicted target vector."""

        return self.predict(features).mean(axis=0)

    def predict_named(
        self,
        features: ArrayLike,
    ) -> dict[str, NDArray[np.float64]]:
        """Return one prediction vector per target name."""

        prediction = self.predict(features)
        return {
            name: prediction[:, index].copy()
            for index, name in enumerate(self.target_names)
        }


def as_bess_dataset(
    training: CSSFDataset | BESSDataset,
    *,
    case: str | None = None,
    validation: CSSFDataset | None = None,
    test: CSSFDataset | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> BESSDataset:
    """Convert generic CSSF datasets to the frozen legacy contract."""

    if isinstance(training, BESSDataset):
        if validation is not None or test is not None:
            raise CSNNTAdapterError(
                "validation/test arguments are forbidden when training is "
                "already a BESSDataset."
            )
        if case is not None and case.strip() != training.case:
            raise CSNNTAdapterError(
                f"case={case!r} conflicts with dataset case={training.case!r}."
            )
        return training

    if not isinstance(training, CSSFDataset):
        raise TypeError(
            "training must be CSSFDataset or BESSDataset."
        )

    normalized_case = "" if case is None else str(case).strip()
    if not normalized_case:
        raise CSNNTAdapterError(
            "case is required when adapting a CSSFDataset."
        )

    if validation is not None and not isinstance(validation, CSSFDataset):
        raise TypeError("validation must be CSSFDataset or None.")
    if test is not None and not isinstance(test, CSSFDataset):
        raise TypeError("test must be CSSFDataset or None.")

    merged_metadata = {
        **dict(training.metadata),
        **({} if metadata is None else dict(metadata)),
    }

    try:
        return BESSDataset(
            case=normalized_case,
            X_train=training.features,
            y_train=training.targets,
            X_validation=(
                None if validation is None else validation.features
            ),
            y_validation=(
                None if validation is None else validation.targets
            ),
            X_test=None if test is None else test.features,
            y_test=None if test is None else test.targets,
            metadata=merged_metadata,
        )
    except DatasetError as exc:
        raise CSNNTAdapterError(
            f"Cannot create BESSDataset: {exc}"
        ) from exc


def fit_csnn_t_surrogate(
    training: CSSFDataset | BESSDataset,
    *,
    case: str | None = None,
    level: SurrogateLevel = SurrogateLevel.OPF,
    validation: CSSFDataset | None = None,
    test: CSSFDataset | None = None,
    target_names: Sequence[str] | None = None,
    n_lambdas: int = 100,
    lam_range: tuple[float, float] = (-12.0, 4.0),
    lam_fixed: float | None = None,
    metadata: Mapping[str, Any] | None = None,
    verify_integrity: bool = True,
    project_root: str | Path = COLAB_PROJECT_ROOT,
) -> CSNNTSurrogateModel:
    """Fit any CSSF level through the unchanged frozen CSNN-T primitive."""

    if not isinstance(level, SurrogateLevel):
        raise TypeError("level must be SurrogateLevel.")

    if isinstance(n_lambdas, bool) or not isinstance(n_lambdas, int):
        raise TypeError("n_lambdas must be an integer.")
    if n_lambdas < 2:
        raise CSNNTAdapterError("n_lambdas must be at least 2.")

    if len(lam_range) != 2:
        raise CSNNTAdapterError("lam_range must contain two values.")
    lam_low = float(lam_range[0])
    lam_high = float(lam_range[1])
    if (
        not math.isfinite(lam_low)
        or not math.isfinite(lam_high)
        or lam_low >= lam_high
    ):
        raise CSNNTAdapterError(
            "lam_range must contain finite increasing log10 bounds."
        )

    if lam_fixed is not None:
        lam_fixed = float(lam_fixed)
        if not math.isfinite(lam_fixed) or lam_fixed <= 0.0:
            raise CSNNTAdapterError(
                "lam_fixed must be finite and positive."
            )

    if verify_integrity:
        verify_frozen_core(project_root)

    dataset = as_bess_dataset(
        training,
        case=case,
        validation=validation,
        test=test,
        metadata=metadata,
    )

    if lam_fixed is None:
        lam_opt, lam_grid, gcv_values = gcv_lambda(
            dataset.X_train,
            dataset.y_train,
            n_lambdas=n_lambdas,
            lam_range=(lam_low, lam_high),
        )
        used_fixed_lambda = False
        diagnostic_n_lambdas = n_lambdas
    else:
        lam_opt = lam_fixed
        lam_grid = np.empty(0, dtype=np.float64)
        gcv_values = np.empty(0, dtype=np.float64)
        used_fixed_lambda = True
        diagnostic_n_lambdas = 0

    legacy_model = fit_csnn_t(
        dataset,
        lam_fixed=lam_opt,
    )

    coefficient_matrix = np.ascontiguousarray(
        legacy_model.H,
        dtype=np.complex128,
    )
    coefficient_matrix.setflags(write=False)

    immutable_legacy_model = CSNNTModel(
        H=coefficient_matrix,
        lam_opt=float(legacy_model.lam_opt),
        case=legacy_model.case,
        M=legacy_model.M,
        n=legacy_model.n,
    )

    diagnostics = CSNNTFitDiagnostics(
        lam_opt=float(lam_opt),
        effective_rank=effective_rank(
            dataset.X_train,
            float(lam_opt),
        ),
        n_lambdas=diagnostic_n_lambdas,
        lam_range=(lam_low, lam_high),
        used_fixed_lambda=used_fixed_lambda,
        lam_grid=lam_grid,
        gcv_values=gcv_values,
    )

    names = _normalized_target_names(
        target_names,
        count=dataset.n,
    )

    model_metadata = {
        **dict(dataset.metadata),
        **({} if metadata is None else dict(metadata)),
        "surrogate_level": level.value,
        "frozen_core": True,
    }

    result = CSNNTSurrogateModel(
        frozen_model=immutable_legacy_model,
        level=level,
        target_names=names,
        training_fingerprint=dataset.fingerprint(),
        diagnostics=diagnostics,
        metadata=model_metadata,
    )

    if verify_integrity:
        verify_frozen_core(project_root)

    return result


__all__ = [
    "CSNNTAdapterError",
    "CSNNTFitDiagnostics",
    "CSNNTSurrogateModel",
    "as_bess_dataset",
    "fit_csnn_t_surrogate",
]
